using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using System.Collections.Immutable;
using System.Text;

namespace ClapInfra.SourceGenerators;

[Generator]
public class SkillRegistrationGenerator : IIncrementalGenerator
{
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var provider = context.SyntaxProvider
            .CreateSyntaxProvider(
                predicate: (node, _) => node is ClassDeclarationSyntax { AttributeLists.Count: > 0 },
                transform: (ctx, _) => GetPackageInfo(ctx))
            .Where(info => info is not null)
            .Collect();

        context.RegisterSourceOutput(provider, GenerateSource);
    }

    private static PackageInfo? GetPackageInfo(GeneratorSyntaxContext ctx)
    {
        var classDecl = (ClassDeclarationSyntax)ctx.Node;
        var symbol = ctx.SemanticModel.GetDeclaredSymbol(classDecl) as INamedTypeSymbol;
        if (symbol is not { IsAbstract: false })
            return null;

        if (!HasSkillSourceAttribute(symbol))
            return null;

        var baseType = FindClapSkillPackageBase(symbol);
        if (baseType is not { TypeArguments.Length: 2 })
            return null;

        var skillContextType = baseType.TypeArguments[0];
        var dslSourceFileType = baseType.TypeArguments[1];

        var methods = symbol.GetMembers()
            .OfType<IMethodSymbol>()
            .Where(m => m is { DeclaredAccessibility: Accessibility.Private, IsStatic: false })
            .ToList();

        var skills = new List<SkillMethodInfo>();

        foreach (var method in methods)
        {
            if (!method.Name.EndsWith("Check", StringComparison.Ordinal))
                continue;
            if (method.ReturnType.SpecialType != SpecialType.System_Boolean)
                continue;
            if (method.Parameters.Length != 1)
                continue;
            if (!SymbolEqualityComparer.Default.Equals(
                    method.Parameters[0].Type, skillContextType))
                continue;

            var skillName = method.Name.Substring(0, method.Name.Length - "Check".Length);

            var generatorMethod = methods.FirstOrDefault(m =>
                m.Name == skillName &&
                m.Parameters.Length == 1 &&
                SymbolEqualityComparer.Default.Equals(
                    m.Parameters[0].Type, skillContextType) &&
                SymbolEqualityComparer.Default.Equals(
                    m.ReturnType, dslSourceFileType));

            if (generatorMethod == null)
                continue;

            skills.Add(new SkillMethodInfo(
                skillName.ToLowerInvariant(),
                method.Name,
                generatorMethod.Name));
        }

        if (skills.Count == 0)
            return null;

        return new PackageInfo(
            symbol.Name,
            symbol.ContainingNamespace.ToDisplayString(),
            skills);
    }

    private static bool HasSkillSourceAttribute(INamedTypeSymbol symbol)
    {
        foreach (var attr in symbol.GetAttributes())
        {
            var cls = attr.AttributeClass;
            while (cls != null)
            {
                if (cls.Name is "SkillSourceAttribute" or "SkillSource" &&
                    cls.ContainingNamespace.ToDisplayString() == "ClapInfra.ClapProfession")
                    return true;
                cls = cls.BaseType;
            }
        }
        return false;
    }

    private static INamedTypeSymbol? FindClapSkillPackageBase(INamedTypeSymbol type)
    {
        var current = type.BaseType;
        while (current != null)
        {
            if (current.Name == "ClapSkillPackage" &&
                current.TypeArguments.Length == 2 &&
                current.ContainingNamespace.ToDisplayString() == "ClapInfra.ClapProfession")
                return current;
            current = current.BaseType;
        }
        return null;
    }

    private static void GenerateSource(
        SourceProductionContext ctx,
        ImmutableArray<PackageInfo?> infos)
    {
        foreach (var info in infos)
        {
            if (info == null)
                continue;
            ctx.AddSource(
                $"{info.ClassName}.SkillRegistration.g.cs",
                GeneratePartialClass(info));
        }
    }

    private static string GeneratePartialClass(PackageInfo info)
    {
        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        sb.AppendLine($"namespace {info.Namespace};");
        sb.AppendLine();
        sb.AppendLine($"partial class {info.ClassName}");
        sb.AppendLine("{");
        sb.AppendLine("    protected override void RegisterSkills()");
        sb.AppendLine("    {");
        foreach (var skill in info.Skills)
        {
            sb.AppendLine($"        RegisterSkill(");
            sb.AppendLine($"            \"{skill.SkillName}\",");
            sb.AppendLine($"            {skill.CheckMethod},");
            sb.AppendLine($"            {skill.GeneratorMethod});");
        }
        sb.AppendLine("    }");
        sb.AppendLine("}");
        return sb.ToString();
    }
}

internal sealed class PackageInfo
{
    public string ClassName { get; }
    public string Namespace { get; }
    public List<SkillMethodInfo> Skills { get; }

    public PackageInfo(string className, string @namespace, List<SkillMethodInfo> skills)
    {
        ClassName = className;
        Namespace = @namespace;
        Skills = skills;
    }
}

internal sealed class SkillMethodInfo
{
    public string SkillName { get; }
    public string CheckMethod { get; }
    public string GeneratorMethod { get; }

    public SkillMethodInfo(string skillName, string checkMethod, string generatorMethod)
    {
        SkillName = skillName;
        CheckMethod = checkMethod;
        GeneratorMethod = generatorMethod;
    }
}
