using System.Collections.Immutable;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;

namespace ClapSourceGenerators.SkillRegistration.BlacksmithOnly
{
    [Generator]
    public class ModifierBindingGenerator : IIncrementalGenerator
    {
        private static readonly SymbolDisplayFormat FullTypeFormat = SymbolDisplayFormat.FullyQualifiedFormat;

        public void Initialize(IncrementalGeneratorInitializationContext context)
        {
            // ── Phase 1: MainProfession 源码 → 收集私有成员 → 生成 [BindingContract] ──
            var mainInSource = context.SyntaxProvider
                .CreateSyntaxProvider(
                    predicate: (node, _) => node is ClassDeclarationSyntax,
                    transform: (ctx, _) => GetMainInfo(ctx))
                .Where(info => info is not null)
                .Select((info, _) => info!);

            context.RegisterSourceOutput(mainInSource.Collect(), GenerateContracts);

            // ── Phase 2: 读 [BindingContract] → 生成 public 字段 + Bind() ──
            var modifierInSource = context.SyntaxProvider
                .CreateSyntaxProvider(
                    predicate: (node, _) => node is ClassDeclarationSyntax,
                    transform: (ctx, _) => GetModifierInfo(ctx))
                .Where(info => info is not null)
                .Select((info, _) => info!);

            var combined = modifierInSource.Collect().Combine(context.CompilationProvider);
            context.RegisterSourceOutput(combined, GenerateModifierSide);
        }

        // ════════════════════════════════════════════════════════════════
        //  Phase 1 helpers
        // ════════════════════════════════════════════════════════════════

        private sealed class MainInfo
        {
            public string ClassName, Namespace, FullTypeName;
            public ImmutableArray<Member> Fields, Properties;
            public MainInfo(string cn, string ns, string ft, ImmutableArray<Member> f, ImmutableArray<Member> p)
            { ClassName = cn; Namespace = ns; FullTypeName = ft; Fields = f; Properties = p; }
        }

        private sealed class Member
        {
            public string Name, TypeFull;
            public bool Flag; // field → IsReadonly, property → HasSetter
            public Member(string n, string t, bool f) { Name = n; TypeFull = t; Flag = f; }
        }

        private static MainInfo? GetMainInfo(GeneratorSyntaxContext ctx)
        {
            var cds = (ClassDeclarationSyntax)ctx.Node;
            var sym = ctx.SemanticModel.GetDeclaredSymbol(cds) as INamedTypeSymbol;
            if (sym is not { IsAbstract: false }) return null;

            var bt = sym.BaseType;
            if (bt == null || bt.TypeArguments.Length != 0
                || bt.ContainingNamespace.ToDisplayString() != "BlacksmithCore.Infra.Profession"
                || bt.Name != "MainProfession")
                return null;

            var fields = ImmutableArray.CreateBuilder<Member>();
            var props = ImmutableArray.CreateBuilder<Member>();

            foreach (var f in sym.GetMembers().OfType<IFieldSymbol>())
                if (f is { DeclaredAccessibility: Accessibility.Private, IsStatic: false } && f.Type.IsReferenceType)
                    fields.Add(new Member(f.Name, f.Type.ToDisplayString(FullTypeFormat), f.IsReadOnly));

            foreach (var p in sym.GetMembers().OfType<IPropertySymbol>())
                if (p is { DeclaredAccessibility: Accessibility.Private, IsStatic: false } && p.Type.IsReferenceType && p.GetMethod != null)
                    props.Add(new Member(p.Name, p.Type.ToDisplayString(FullTypeFormat), p.SetMethod != null));

            if (fields.Count == 0 && props.Count == 0) return null;

            return new MainInfo(sym.Name, sym.ContainingNamespace.ToDisplayString(),
                sym.ToDisplayString(FullTypeFormat), fields.ToImmutable(), props.ToImmutable());
        }

        private static void GenerateContracts(SourceProductionContext ctx, ImmutableArray<MainInfo> mains)
        {
            foreach (var m in mains)
            {
                var sb = new StringBuilder();
                sb.AppendLine("// <auto-generated/>");
                sb.AppendLine("using BlacksmithCore.Infra.Attributes.Profession;");
                sb.AppendLine($"namespace {m.Namespace};");
                sb.AppendLine();
                foreach (var f in m.Fields)
                    sb.AppendLine($"[BindingContract(\"{f.Name}\", \"{f.TypeFull}\", true, {(f.Flag ? "true" : "false")})]");
                foreach (var p in m.Properties)
                    sb.AppendLine($"[BindingContract(\"{p.Name}\", \"{p.TypeFull}\", false, {(p.Flag ? "true" : "false")})]");
                sb.AppendLine($"partial class {m.ClassName} {{ }}");

                ctx.AddSource($"{m.Namespace}.{m.ClassName}.Contract.g.cs", sb.ToString());
            }
        }

        // ════════════════════════════════════════════════════════════════
        //  Phase 2 helpers
        // ════════════════════════════════════════════════════════════════

        private sealed class ModifierInfo
        {
            public string ClassName, Namespace, TargetName;
            public ModifierInfo(string c, string ns, string t) { ClassName = c; Namespace = ns; TargetName = t; }
        }

        private static ModifierInfo? GetModifierInfo(GeneratorSyntaxContext ctx)
        {
            var cds = (ClassDeclarationSyntax)ctx.Node;
            var sym = ctx.SemanticModel.GetDeclaredSymbol(cds) as INamedTypeSymbol;
            if (sym is not { IsAbstract: false }) return null;

            var bt = sym.BaseType;
            if (bt == null || bt.TypeArguments.Length != 0
                || bt.ContainingNamespace.ToDisplayString() != "BlacksmithCore.Infra.Profession"
                || bt.Name != "ProfessionModifier")
                return null;

            var attr = sym.GetAttributes().FirstOrDefault(a =>
                a.AttributeClass?.Name == "IsProfessionModifier"
                || a.AttributeClass?.ToDisplayString() == "BlacksmithCore.Infra.Attributes.Profession.IsProfessionModifier");
            if (attr == null) return null;

            var target = attr.ConstructorArguments.FirstOrDefault().Value?.ToString();
            if (target is null or "") return null;

            return new ModifierInfo(sym.Name, sym.ContainingNamespace.ToDisplayString(), target);
        }

        private static void GenerateModifierSide(
            SourceProductionContext ctx,
            (ImmutableArray<ModifierInfo> Modifiers, Compilation Compilation) data)
        {
            var comp = data.Compilation;

            var mainBase = comp.GetTypeByMetadataName("BlacksmithCore.Infra.Profession.MainProfession");
            if (mainBase == null) return;

            var contractAttr = comp.GetTypeByMetadataName("BlacksmithCore.Infra.Attributes.Profession.BindingContractAttribute");

            foreach (var mod in data.Modifiers)
            {
                var target = FindMainByName(comp, mainBase, mod.TargetName);
                if (target == null) continue;
                var targetFull = target.ToDisplayString(FullTypeFormat);

                // Read [BindingContract] attributes
                var fields = new List<Member>();
                var props = new List<Member>();
                foreach (var a in target.GetAttributes())
                {
                    bool match = contractAttr != null
                        ? SymbolEqualityComparer.Default.Equals(a.AttributeClass, contractAttr)
                        : a.AttributeClass?.Name == "BindingContract";
                    if (!match) continue;
                    var args = a.ConstructorArguments;
                    if (args.Length < 4) continue;
                    var n = args[0].Value?.ToString();
                    var t = args[1].Value?.ToString();
                    var isF = args[2].Value as bool?;
                    var fl = args[3].Value as bool?;
                    if (n == null || t == null || isF == null || fl == null) continue;
                    if (isF.Value) fields.Add(new Member(n, t, fl.Value));
                    else props.Add(new Member(n, t, fl.Value));
                }
                if (fields.Count == 0 && props.Count == 0) continue;

                // Generate partial class
                var sb = new StringBuilder();
                sb.AppendLine("// <auto-generated/>");
                sb.AppendLine("#nullable enable");
                sb.AppendLine();
                sb.AppendLine("using System;");
                sb.AppendLine("using System.Runtime.CompilerServices;");
                sb.AppendLine("using BlacksmithCore.Infra.Profession;");
                sb.AppendLine($"namespace {mod.Namespace};");
                sb.AppendLine();
                sb.AppendLine($"partial class {mod.ClassName}");
                sb.AppendLine("{");

                // UnsafeAccessor extern methods for private fields
                foreach (var f in fields)
                {
                    sb.AppendLine($"    [UnsafeAccessor(UnsafeAccessorKind.Field, Name = \"{f.Name}\")]");
                    sb.AppendLine($"    private static extern ref {f.TypeFull} __ref_{f.Name}({targetFull} __t);");
                }

                // UnsafeAccessor extern methods for private property accessors
                foreach (var p in props)
                {
                    sb.AppendLine($"    [UnsafeAccessor(UnsafeAccessorKind.Method, Name = \"get_{p.Name}\")]");
                    sb.AppendLine($"    private static extern {p.TypeFull} __get_{p.Name}({targetFull} __t);");
                    if (p.Flag) // HasSetter
                    {
                        sb.AppendLine($"    [UnsafeAccessor(UnsafeAccessorKind.Method, Name = \"set_{p.Name}\")]");
                        sb.AppendLine($"    private static extern void __set_{p.Name}({targetFull} __t, {p.TypeFull} value);");
                    }
                }
                sb.AppendLine();
                // Captured storage (private — accessed via UnsafeAccessor or within this class)
                foreach (var f in fields)
                    sb.AppendLine($"    private {f.TypeFull} {f.Name} = null!;");
                foreach (var p in props)
                {
                    sb.AppendLine($"    private Func<{p.TypeFull}> {p.Name} = null!;");
                    if (p.Flag)
                        sb.AppendLine($"    private Action<{p.TypeFull}> Set{p.Name} = null!;");
                }

                // Bind method
                sb.AppendLine();
                sb.AppendLine("    public override void Bind(MainProfession package)");
                sb.AppendLine("    {");
                sb.AppendLine($"        var target = ({targetFull})package;");
                foreach (var f in fields)
                    sb.AppendLine($"        this.{f.Name} = __ref_{f.Name}(target);");
                foreach (var p in props)
                {
                    sb.AppendLine($"        this.{p.Name} = () => __get_{p.Name}(target);");
                    if (p.Flag)
                        sb.AppendLine($"        this.Set{p.Name} = v => __set_{p.Name}(target, v);");
                }
                sb.AppendLine("    }");
                sb.AppendLine("}");

                ctx.AddSource($"{mod.Namespace}.{mod.ClassName}.Binding.g.cs", sb.ToString());
            }
        }

        private static INamedTypeSymbol? FindMainByName(Compilation comp, INamedTypeSymbol baseType, string name)
        {
            var visited = new HashSet<ISymbol>(SymbolEqualityComparer.Default);
            return Walk(comp.GlobalNamespace, baseType, name, visited);
        }

        private static INamedTypeSymbol? Walk(INamespaceOrTypeSymbol c, INamedTypeSymbol baseType, string name, HashSet<ISymbol> v)
        {
            if (!v.Add(c)) return null;
            foreach (var m in c.GetMembers())
            {
                if (m is INamedTypeSymbol t)
                {
                    if (t is { IsAbstract: false } && t.Name == name && t.BaseType != null
                        && SymbolEqualityComparer.Default.Equals(t.BaseType, baseType))
                        return t;
                    var r = Walk(t, baseType, name, v);
                    if (r != null) return r;
                }
                else if (m is INamespaceSymbol ns)
                {
                    var r = Walk(ns, baseType, name, v);
                    if (r != null) return r;
                }
            }
            return null;
        }
    }
}
