<Project Sdk="Microsoft.NET.Sdk">

	<ItemGroup>
	  <ProjectReference Include="..\..\ClapInfra\ClapInfra.csproj" />
	  <ProjectReference Include="..\..\ClapInfra.SourceGenerators\ClapInfra.SourceGenerators.csproj"
	                    OutputItemType="Analyzer"
	                    ReferenceOutputAssembly="false" />
	</ItemGroup>

	<PropertyGroup>
		<TargetFramework>net8.0</TargetFramework>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
	</PropertyGroup>

</Project>
